# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status2Enum(object):

    """Implementation of the 'status2' enum.

    TODO: type enum description here.

    Attributes:
        AVAILABLE: TODO: type description here.
        PENDING: TODO: type description here.
        SOLD: TODO: type description here.

    """

    AVAILABLE = 'available'

    PENDING = 'pending'

    SOLD = 'sold'
