# -*- coding: utf-8 -*-

"""
swaggerpetstore

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class User(object):

    """Implementation of the 'User' model.

    TODO: type model description here.

    Attributes:
        id (long|int): TODO: type description here.
        username (string): TODO: type description here.
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        email (string): TODO: type description here.
        password (string): TODO: type description here.
        phone (string): TODO: type description here.
        user_status (int): User Status

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "username": 'username',
        "first_name": 'firstName',
        "last_name": 'lastName',
        "email": 'email',
        "password": 'password',
        "phone": 'phone',
        "user_status": 'userStatus'
    }

    def __init__(self,
                 id=None,
                 username=None,
                 first_name=None,
                 last_name=None,
                 email=None,
                 password=None,
                 phone=None,
                 user_status=None):
        """Constructor for the User class"""

        # Initialize members of the class
        self.id = id
        self.username = username
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.password = password
        self.phone = phone
        self.user_status = user_status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        username = dictionary.get('username')
        first_name = dictionary.get('firstName')
        last_name = dictionary.get('lastName')
        email = dictionary.get('email')
        password = dictionary.get('password')
        phone = dictionary.get('phone')
        user_status = dictionary.get('userStatus')

        # Return an object of this model
        return cls(id,
                   username,
                   first_name,
                   last_name,
                   email,
                   password,
                   phone,
                   user_status)
